{% set name = "mail-parser" %}
{% set version = "4.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c44a53863a5db1dd266565686169384b1835a9d115d3b50cf1f78fb096090f4c

build:
  number: 0
  entry_points:
    - mailparser = mailparser.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - ipaddress >=1.0.23  # [py<33]
    - python
    - simplejson >=3.17.0
    - six >=1.14.0

test:
  imports:
    - mailparser
  commands:
    - pip check
    - mailparser --help
  requires:
    - pip

about:
  home: https://github.com/SpamScope/mail-parser
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Tokenizer for raw mails'
  description: |
    mail-parser is not only a wrapper for email Python Standard Library. 
    It give you an easy way to pass from raw mail to Python object that
    you can use in your code. 
  doc_url: https://github.com/SpamScope/mail-parser
  dev_url: https://github.com/SpamScope/mail-parser

extra:
  recipe-maintainers:
    - jan-janssen
